# Generated by Django 4.1.4 on 2024-03-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asin", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("price", models.FloatField(max_length=10)),
                ("deal", models.FloatField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
