# Generated by Django 4.1.4 on 2024-03-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_productdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetails",
            name="dimensions",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="productdetails", name="profit", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="profit_Percentage",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="productdetails", name="salePrice", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="salesRank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="sales_Count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="sellers_Count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="variation_count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="weigt",
            field=models.FloatField(max_length=10),
        ),
    ]
