# Generated by Django 4.1.4 on 2024-03-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_productdetailsca_productdetailsuk_productdetailsus"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="asin",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
