# Generated by Django 4.2.11 on 2024-04-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_productdetails_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='amzPrices',
            field=models.TextField(blank=True, null=True),
        ),
    ]
